### PR TITLE
XandyBot v1.2.0

### PR DESCRIPTION
**Pull request by brainfrozeno00o**
- Now using PostgreSQL in storing the needed data such as the quotes, images, etc.
- Now having the `%clown` command which gives a random quote at will, and it should not affect the scheduled sending of quotes
- Now having the `%pogi` command which gives a random pic at will

**NOTE**: This will now be the last pull request for this repository as XandyBot will now migrate to using Node.js and utilize the slash commands.

### CODE REVIEW

**Comment by brainfrozeno00o** [comment]
Currently at draft for now, will open this at 27/11/2021, please take note @xanderapark; you may view the code only for now, thank you

**Comment by brainfrozeno00o** [comment]
@xanderapark this is now ready for review. Please check before merging. Thank you.

**Comment by xanderapark** [comment]
Alright, looks good. When will the implementation of Node.js begin also the utilization of slash commands?

**Comment by brainfrozeno00o** [comment]
The transition to Node.js will most likely start next month. For now, we can archive this repository and create a separate repository for the Node.js implementation.

**Pull request merged**
