### PR TITLE
XDY-013, XDY-014: Adding the %clown and %pogi commands

### PR DESCRIPTION
**Pull request by brainfrozeno00o**
Tasks done with relation to the tickets:

- Added the `%clown` command which basically sends a random Xander quote at will - this **SHOULD NOT** affect the scheduled sending of quotes; quotes can be repeated
- Added the `%pogi` command which basically sends a random image of Xander - images can be repeated; a message will send first prior to sending the image itself

### CODE REVIEW

**Comment by brainfrozeno00o** [comment]
Will deploy UAT bot with the added features in a while and will also most likely open this pull request for review on 20-11-2021

**Comment by brainfrozeno00o** [comment]
@xanderapark this is now ready for your review, will also shut down the XandyBotUAT as well

**Comment by xanderapark** [comment]
I notice that when testing the %pogi command, xandybot will state it is an unknown command, but will still proceed to send a photo

**Comment by brainfrozeno00o** [comment]
> I notice that when testing the %pogi command, xandybot will state it is an unknown command, but will still proceed to send a photo

@xanderapark, this is because both XandyBot and XandyBotUAT were both online. XandyBot will not register `%pogi` and even `%clown` as a command since the commands (i.e. the logic needed to make the two commands work) are currently not yet there in XandyBot. The one that sends the pictures in this case is XandyBotUAT.

**Pull request merged**
